// Standing guard: no user-typed text may reach the page unescaped.
//
// PLAIN ENGLISH: `innerHTML` pastes text into the page AS HTML, meaning the
// browser obeys any instructions hidden inside it. That is only dangerous
// when the text came from a PERSON (a typed team name, a pasted share code)
// rather than from our own data files. This test re-checks that every such
// spot still runs user text through escName() first.
//
// If this fails, someone added a new place where typed text is pasted into
// the page without cleaning it. Wrap the value in escName().
const fs = require('fs');
const app = fs.readFileSync(require('path').join(__dirname,'..','app.js'), 'utf8');
let pass = 0, fail = 0;
const t = (n, c, x) => { c ? pass++ : fail++; console.log((c ? '✅' : '❌ FAIL'), n, x ? '— ' + x : ''); };

// 1. The cleaning function must still exist and still handle all 5 characters
//    that can turn text into instructions.
const hasEsc = /function escName\s*\(/.test(app);
t('escName() cleaning function still exists', hasEsc);
if (hasEsc) {
  const body = app.slice(app.indexOf('function escName'), app.indexOf('function escName') + 300);
  t('escName still escapes & < > " \'',
    ['&amp;','&lt;','&gt;','&quot;','&#39;'].every(e => body.includes(e)));
}

// 2. Team names (the only free text a user types) must be escaped everywhere
//    they are pasted into the page.
const nameRenders = [...app.matchAll(/\$\{[^}]*\bt\.name\b[^}]*\}/g)].map(m => m[0]);
t('every team-name render is escaped',
  nameRenders.length > 0 && nameRenders.every(r => r.includes('escName')),
  nameRenders.join(' | ') || 'no team-name renders found');

// 3. Share codes must stay lookup-only: their fields are used to FIND real
//    Pokemon/moves, never pasted into the page. IVs must stay numbers.
const importFn = app.slice(app.indexOf('function loadSquadFromCode'),
                           app.indexOf('function loadSquadFromCode') + 1400);
t('share code fields are lookup-only (never rendered)',
  !/innerHTML[\s\S]{0,200}entry\./.test(importFn));
t('share code IVs are forced to numbers',
  /\+entry\.iv\.atk/.test(importFn) && /Math\.min\(15/.test(importFn));

// 4. Nothing may paste raw INCOMING user text into the page.
//    Direction matters: the share code we DISPLAY is generated by our own
//    btoa() (base64 = letters/digits/+/=, nothing that can become an
//    instruction), so it is safe. What must never be pasted unescaped is
//    text that arrived FROM a person: typed names, imported code contents.
const raw = [...app.matchAll(/innerHTML\s*=\s*[`'"][^;]*/g)]
  .map(m => m[0])
  .filter(s => /\bt\.name\b|\bentry\.name\b|\bentry\.s\b|\bminimal\b|IMPORT_INPUT|importValue/.test(s))
  .filter(s => !s.includes('escName'));
t('no unescaped incoming user text reaches innerHTML', raw.length === 0, raw.join(' | ') || 'clean');

// 4b. The displayed share code must stay base64-generated, never user-supplied.
const shareBlock = app.slice(app.indexOf('SHARE_BTN.addEventListener'),
                             app.indexOf('SHARE_BTN.addEventListener') + 400);
t('displayed share code comes from our own encoder',
  /const code\s*=\s*encodeSquadCode\(\)/.test(shareBlock));

// 5. The app must not gain URL-parameter input without a deliberate decision.
//    (Reading text out of the address bar is a classic way user text sneaks in.)
t('app still reads no text from the URL',
  !/URLSearchParams|location\.search|location\.hash/.test(app));

console.log(); console.log(pass + '/' + (pass + fail) + ' PASSED');
process.exit(fail ? 1 : 0);
